import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://apply.mykaleidoscope.com/program/sdet-test-scholarship');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('myemailofficial@gmail.com');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('josh');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill('english');
  await page.getByRole('textbox', { name: '1 (702) 123-' }).click();
  await page.getByRole('textbox', { name: '1 (702) 123-' }).fill('+1 (897) 548-1273');
  await page.getByRole('textbox', { name: '1 (702) 123-' }).press('Tab');
  await page.getByRole('textbox', { name: 'Create a Password' }).click();
  await page.getByRole('textbox', { name: 'Create a Password' }).fill('Apply@1010d');
  await page.getByRole('checkbox', { name: 'I confirm that I am at least' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/application/start');
  await page.locator('.m_d8b5e363').click();
  await page.locator('.m_d8b5e363').click();
  await page.locator('.m_c44ba933').first().click();
  await page.getByRole('textbox', { name: 'Street Address', exact: true }).click();
  await page.getByRole('textbox', { name: 'Street Address', exact: true }).fill('street in pune');
  await page.getByRole('textbox', { name: 'Additional Street Address' }).click();
  await page.getByRole('textbox', { name: 'Additional Street Address' }).fill('');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/application/start');
  await page.getByRole('textbox', { name: 'Additional Street Address' }).fill('near panjab');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/application/start');
  await page.getByRole('textbox', { name: 'Additional Street Address' }).fill('near panjab dhaba');
  await page.getByRole('textbox', { name: 'State (Full)' }).click();
  await page.getByRole('textbox', { name: 'State (Full)' }).fill('Maine');
  await page.getByRole('option', { name: 'Maine' }).click();
  await page.getByRole('textbox', { name: 'City' }).click();
  await page.getByRole('textbox', { name: 'City' }).fill('pune');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/application/start');
  await page.getByRole('textbox', { name: 'City' }).fill('pune ');
  await page.locator('.m_d8b5e363').click();
  await page.locator('.m_c44ba933').first().click();
  await page.locator('.m_c44ba933').first().click();
  await page.locator('.m_c44ba933').first().click();
  await page.locator('.m_c44ba933').first().click();
  await page.locator('.m_c44ba933').first().dblclick();
  await page.locator('.m_c44ba933').first().click();
  await page.locator('.m_d8b5e363').click();
  await page.getByRole('textbox', { name: 'City' }).fill('pune');
  await page.getByRole('textbox', { name: 'City' }).press('Tab');
  await page.getByRole('textbox', { name: 'Zip Code' }).fill('411057');
  await page.getByRole('textbox', { name: 'Zip Code' }).press('Tab');
  await page.getByRole('textbox', { name: 'Country' }).fill('indi');
  await page.getByRole('option', { name: 'India' }).click();
  await page.getByRole('textbox', { name: 'Country' }).press('Tab');
  await page.getByRole('button', { name: 'Next Page' }).click();
  await page.getByRole('button', { name: 'Add Entry' }).click();
  await page.getByRole('textbox', { name: 'Extracurricular Activity Name' }).click();
  await page.getByRole('textbox', { name: 'Extracurricular Activity Name' }).fill('Dancing');
  await page.getByRole('textbox', { name: 'Total Number of Years Involved' }).click();
  await page.getByRole('textbox', { name: 'Total Number of Years Involved' }).fill('2');
  await page.getByRole('textbox', { name: 'List any leadership roles,' }).click();
  await page.getByRole('textbox', { name: 'List any leadership roles,' }).fill('First Prize in de');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/e206520d-2374-4b89-84a6-6e55f33ff8e1');
  await page.getByRole('textbox', { name: 'List any leadership roles,' }).fill('First Prize in departmental dance');
  await page.getByRole('textbox', { name: 'Description of Involvement' }).click();
  await page.getByRole('textbox', { name: 'Description of Involvement' }).fill('Participated in all the events and finally got first prize in dance');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Next Page' }).click();
  await expect(page.locator('#form-renderer')).toContainText('Please add at least 2 entries');
  await page.getByRole('button', { name: 'Add Entry' }).click();
  await page.getByRole('textbox', { name: 'Extracurricular Activity Name' }).click();
  await page.getByRole('textbox', { name: 'Extracurricular Activity Name' }).fill('Best 100m runner');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/e206520d-2374-4b89-84a6-6e55f33ff8e1');
  await page.getByRole('textbox', { name: 'Extracurricular Activity Name' }).fill('Best 100m runner1');
  await page.getByRole('textbox', { name: 'Total Number of Years Involved' }).click();
  await page.getByRole('textbox', { name: 'Total Number of Years Involved' }).fill('1');
  await page.getByRole('textbox', { name: 'List any leadership roles,' }).click();
  await page.getByRole('textbox', { name: 'List any leadership roles,' }).fill('First prize in 100m runni');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/e206520d-2374-4b89-84a6-6e55f33ff8e1');
  await page.getByRole('textbox', { name: 'List any leadership roles,' }).fill('First prize in 100m running event');
  await page.getByRole('textbox', { name: 'Description of Involvement' }).click();
  await page.getByRole('textbox', { name: 'Description of Involvement' }).fill('I was first in al');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/e206520d-2374-4b89-84a6-6e55f33ff8e1');
  await page.getByRole('textbox', { name: 'Description of Involvement' }).fill('I was first from all');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/e206520d-2374-4b89-84a6-6e55f33ff8e1');
  await page.getByRole('textbox', { name: 'Description of Involvement' }).fill('I was first from all departments in ');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/e206520d-2374-4b89-84a6-6e55f33ff8e1');
  await page.getByRole('textbox', { name: 'Description of Involvement' }).fill('I was first from all departments in 100m running event');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button', { name: 'Add Entry' }).click();
  await page.getByRole('textbox', { name: 'Extracurricular Activity Name' }).click();
  await page.getByRole('textbox', { name: 'Extracurricular Activity Name' }).fill('Best Singer Award');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/e206520d-2374-4b89-84a6-6e55f33ff8e1');
  await page.getByRole('textbox', { name: 'Total Number of Years Involved' }).click();
  await page.getByRole('textbox', { name: 'Total Number of Years Involved' }).fill('2');
  await page.getByRole('textbox', { name: 'List any leadership roles,' }).click();
  await page.getByRole('textbox', { name: 'List any leadership roles,' }).fill('Second Prize in sing');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/e206520d-2374-4b89-84a6-6e55f33ff8e1');
  await page.getByRole('textbox', { name: 'List any leadership roles,' }).fill('Second Prize in singing event');
  await page.getByRole('textbox', { name: 'Description of Involvement' }).click();
  await page.getByRole('textbox', { name: 'Description of Involvement' }).fill('I got second prize in sin');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/e206520d-2374-4b89-84a6-6e55f33ff8e1');
  await page.getByRole('textbox', { name: 'Description of Involvement' }).fill('I got second prize in singing event after m');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/e206520d-2374-4b89-84a6-6e55f33ff8e1');
  await page.getByRole('textbox', { name: 'Description of Involvement' }).fill('I got second prize in singing event.');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/e206520d-2374-4b89-84a6-6e55f33ff8e1');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button', { name: 'Add Entry' }).click();
  await page.getByRole('textbox', { name: 'Extracurricular Activity Name' }).click();
  await page.getByRole('textbox', { name: 'Extracurricular Activity Name' }).fill('Debate competion');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/e206520d-2374-4b89-84a6-6e55f33ff8e1');
  await page.getByRole('textbox', { name: 'Total Number of Years Involved' }).click();
  await page.getByRole('textbox', { name: 'Total Number of Years Involved' }).fill('1');
  await page.getByRole('textbox', { name: 'List any leadership roles,' }).click();
  await page.getByRole('textbox', { name: 'List any leadership roles,' }).fill('First prize in debate com');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/e206520d-2374-4b89-84a6-6e55f33ff8e1');
  await page.getByRole('textbox', { name: 'List any leadership roles,' }).fill('First prize in debate competion');
  await page.getByRole('textbox', { name: 'List any leadership roles,' }).click();
  await page.getByRole('textbox', { name: 'List any leadership roles,' }).fill('First prize in debate con');
  await page.getByRole('textbox', { name: 'List any leadership roles,' }).press('ArrowUp');
  await page.getByRole('textbox', { name: 'List any leadership roles,' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'List any leadership roles,' }).click();
  await page.getByRole('textbox', { name: 'List any leadership roles,' }).fill('First prize in debate event');
  await page.getByRole('textbox', { name: 'Description of Involvement' }).click();
  await page.getByRole('textbox', { name: 'Description of Involvement' }).fill('Debate event on ');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/e206520d-2374-4b89-84a6-6e55f33ff8e1');
  await page.getByRole('textbox', { name: 'Description of Involvement' }).fill('Debate event on ""');
  await page.getByRole('textbox', { name: 'Description of Involvement' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Description of Involvement' }).fill('Debate event on "free college ducation"');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/e206520d-2374-4b89-84a6-6e55f33ff8e1');
  await page.getByRole('textbox', { name: 'Description of Involvement' }).fill('Debate event on "free college education"');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/e206520d-2374-4b89-84a6-6e55f33ff8e1');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Next Page' }).click();
  await page.getByRole('textbox', { name: 'High School Name' }).click();
  await page.getByRole('textbox', { name: 'High School Name' }).fill('Shivaji Science Arts junior college');
  await page.getByRole('textbox', { name: 'High School Street Address', exact: true }).click();
  await page.getByRole('textbox', { name: 'High School Street Address', exact: true }).fill('Anandwan square ');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/d61ea0fe-5552-41f0-9de7-e358e7f82552');
  await page.getByRole('textbox', { name: 'Additional High School Street' }).click();
  await page.getByRole('textbox', { name: 'Additional High School Street' }).fill('Tilak ward');
  await page.getByRole('textbox', { name: 'High School City' }).click();
  await page.getByRole('textbox', { name: 'High School City' }).fill('Warora');
  await page.getByRole('textbox', { name: 'High School State (Full)' }).click();
  await page.getByRole('textbox', { name: 'High School State (Full)' }).fill('Ma');
  await page.getByText('Maine').click();
  await page.getByRole('textbox', { name: 'High School State (Full)' }).press('Tab');
  await page.getByRole('textbox', { name: 'High School Zip Code' }).fill('422907');
  await page.getByRole('textbox', { name: 'High School Zip Code' }).press('Tab');
  await page.getByRole('textbox', { name: 'GPA' }).fill('8');
  await page.getByRole('textbox', { name: 'GPA' }).press('Tab');
  await page.getByRole('button').filter({ hasText: /^$/ }).first().click();
  await page.getByRole('textbox', { name: 'Year of High School Graduation' }).fill('1008');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/d61ea0fe-5552-41f0-9de7-e358e7f82552');
  await page.getByRole('textbox', { name: 'Year of High School Graduation' }).fill('10082012');
  await page.getByRole('textbox', { name: 'Year of High School Graduation' }).press('Tab');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('textbox', { name: 'Year of High School Graduation' }).click();
  await page.getByRole('textbox', { name: 'Year of High School Graduation' }).fill('01/07/2012');
  await page.getByRole('textbox', { name: 'Year of High School Graduation' }).press('Tab');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('textbox', { name: 'Year of High School Graduation' }).click();
  await page.getByRole('textbox', { name: 'Year of High School Graduation' }).fill('2012');
  await page.getByRole('textbox', { name: 'Year of High School Graduation' }).press('Tab');
  await page.getByRole('textbox', { name: 'Year of High School Graduation' }).click();
  await page.getByRole('button', { name: '6 January 2012', exact: true }).click();
  await page.getByRole('textbox', { name: 'Year of High School Graduation' }).press('Tab');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('textbox', { name: 'Year of High School Graduation' }).click();
  await page.getByRole('textbox', { name: 'Year of High School Graduation' }).fill('2012');
  await page.getByRole('textbox', { name: 'Year of High School Graduation' }).press('Tab');
  await page.getByRole('button', { name: 'Upload File' }).click();
  await page.getByRole('button', { name: 'Upload File' }).setInputFiles('My School Transcript.pdf');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/d61ea0fe-5552-41f0-9de7-e358e7f82552');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Next Page' }).click();
  
  await page.getByRole('checkbox', { name: 'Cars' }).check();
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/23120c9a-649e-4e17-94f8-7ae5d9f8cc9c');
  await expect(page.getByRole('textbox', { name: 'Essay about Cars' })).toBeVisible();
  await page.getByRole('checkbox', { name: 'Animals' }).check();
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/23120c9a-649e-4e17-94f8-7ae5d9f8cc9c');
  await page.getByRole('checkbox', { name: 'Cars' }).uncheck();
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/23120c9a-649e-4e17-94f8-7ae5d9f8cc9c');
  await page.getByRole('checkbox', { name: 'Animals' }).uncheck();
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/23120c9a-649e-4e17-94f8-7ae5d9f8cc9c');
  await page.getByRole('checkbox', { name: 'Animals' }).check();
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/23120c9a-649e-4e17-94f8-7ae5d9f8cc9c');
  await expect(page.getByRole('textbox', { name: 'Essay about Animals' })).toBeVisible();
  await page.getByRole('checkbox', { name: 'Animals' }).uncheck();
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/23120c9a-649e-4e17-94f8-7ae5d9f8cc9c');
  await page.getByRole('checkbox', { name: 'School' }).check();
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/23120c9a-649e-4e17-94f8-7ae5d9f8cc9c');
  await expect(page.getByRole('textbox', { name: 'Essay about School' })).toBeVisible();
  await page.getByRole('checkbox', { name: 'School' }).uncheck();
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/23120c9a-649e-4e17-94f8-7ae5d9f8cc9c');
  await page.getByRole('checkbox', { name: 'Other' }).check();
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/23120c9a-649e-4e17-94f8-7ae5d9f8cc9c');
  await expect(page.getByRole('textbox', { name: 'Provide an essay about any' })).toBeVisible();
  await page.getByRole('checkbox', { name: 'Other' }).uncheck();
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/23120c9a-649e-4e17-94f8-7ae5d9f8cc9c');
  await page.getByRole('checkbox', { name: 'Animals' }).check();
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/23120c9a-649e-4e17-94f8-7ae5d9f8cc9c');
  await page.getByRole('checkbox', { name: 'School' }).check();
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/23120c9a-649e-4e17-94f8-7ae5d9f8cc9c');
  await page.getByRole('textbox', { name: 'Essay about Animals' }).click();
  await page.getByRole('textbox', { name: 'Essay about Animals' }).fill('I want to write ');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/23120c9a-649e-4e17-94f8-7ae5d9f8cc9c');
  await page.getByRole('textbox', { name: 'Essay about Animals' }).fill('I want to write eassy about Animals');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/23120c9a-649e-4e17-94f8-7ae5d9f8cc9c');
  await page.getByRole('textbox', { name: 'Essay about Animals' }).press('Tab');
  await page.getByRole('textbox', { name: 'Essay about School' }).fill('I want to write e');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/23120c9a-649e-4e17-94f8-7ae5d9f8cc9c');
  await page.getByRole('textbox', { name: 'Essay about School' }).fill('I want to write eassy about schools');
  await page.goto('https://apply.mykaleidoscope.com/program/a0DTP00000H3PUy2AN/applicant/application/a0ETP0000098bbW2AQ/page/23120c9a-649e-4e17-94f8-7ae5d9f8cc9c');
  await page.getByRole('textbox', { name: 'Essay about School' }).fill('I want to write eassy about school');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Next Page' }).click();

  
  await page.getByRole('tab', { name: 'Documents' }).click();
  await page.getByRole('tab', { name: 'Application' }).click();
  const page1Promise = page.waitForEvent('popup');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Print Application' }).click();
  const page1 = await page1Promise;
  const download = await downloadPromise;
  await page.getByRole('link', { name: 'Continue Application' }).click();
  await page.getByRole('button', { name: 'Next Page' }).click();
  await page.getByRole('button', { name: 'Next Page' }).click();
  await page.getByRole('button', { name: 'Next Page' }).click();
  await page.getByRole('button', { name: 'Next Page' }).click();
  await page.getByRole('button', { name: '1.Lets get to know you! Edit' }).click();
  await page.locator('.m_d8b5e363').click();
  await page.locator('.m_c44ba933').click();
  await page.locator('.m_d8b5e363').click();
  await page.getByTestId('overview-scroll-area').click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.getByRole('button', { name: '1.Lets get to know you! Edit' }).click();
  await page.getByRole('button', { name: '2.Extracurricular Activities Edit' }).click();
  await page.getByRole('button', { name: '2.Extracurricular Activities Edit' }).click();
  await page.getByRole('button', { name: '3.High School Information Edit' }).click();
  await page.getByRole('button', { name: '3.High School Information Edit' }).click();
  await page.getByRole('button', { name: '4.Essay Edit' }).click();
  await page.getByRole('button', { name: '4.Essay Edit' }).click();
  const page2Promise = page.waitForEvent('popup');
  const download1Promise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Print Application' }).click();
  const page2 = await page2Promise;
  const download1 = await download1Promise;
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.goto('https://apply.mykaleidoscope.com/applicant/applications');
  await page.getByRole('button', { name: 'Submitted (1)' }).click();
  await page.getByRole('button', { name: 'View Application' }).click();
  await expect(page.getByRole('link', { name: 'Continue Application' })).toBeVisible();
  await expect(page.getByTestId('overview-scroll-area').getByRole('link')).toContainText('Continue Application');
  await expect(page.getByTestId('overview-scroll-area').getByRole('link')).toMatchAriaSnapshot(`- text: Continue Application`);
});